version: "3"
services:
  web:
    image: node:14.15
    depends_on:
      - api
    restart: always
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./web:/app
    command: /bin/bash -c 'npm install && npm run dev'
  api:
    image: node:14.15
    depends_on:
      - db
    restart: always
    working_dir: /app
    volumes:
      - ./api:/app
    command: /bin/bash -c 'npm install && yarn typeorm migration:run && npm run dev '
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "33061:3306"
    restart: always
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
    driver: local
