version: "3.8"
services:
  web:
    build: ./web
    depends_on:
      - api
    restart: always
    ports:
      - 3000:3000
  api:
    build: ./api
    depends_on:
      - db
    restart: always
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "33061:3306"
    restart: always
    volumes:
      - db-docker:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
volumes:
  db-docker:
    driver: local
